import { getSessionJudge } from "../../../lib/auth";
import { redirect } from "next/navigation";
import Link from "next/link";
import JudgeLoginForm from "./LoginForm";

export default async function JudgeLoginPage() {
  const judge = await getSessionJudge();

  // If already logged in, redirect directly to the panel
  if (judge) {
    redirect("/judge/panel");
  }

  return (
    <div className="min-h-screen bg-zinc-50 flex flex-col font-sans">
      
      {/* Top Header */}
      <header className="w-full bg-[#E61E32] border-b border-[#c91527] px-6 py-4 flex items-center justify-between shadow-sm shrink-0">
        <div className="flex items-center gap-2 text-white text-lg tracking-tight">
          <span className="font-semibold text-white/80">HackOS Jury Portal</span>
          <span className="text-white/40 font-light">/</span>
          <span className="font-bold text-white">Login</span>
        </div>
        <Link 
          href="/"
          className="text-xs text-white/80 hover:text-white font-bold transition-colors uppercase tracking-wider"
        >
          Back to Home
        </Link>
      </header>

      {/* Main Container */}
      <main className="flex-1 flex flex-col items-center justify-center p-6 md:p-8 animate-in fade-in duration-200">
        <div className="w-full max-w-sm bg-white border border-zinc-300 rounded-none shadow-sm hover:shadow-md transition-all p-6 space-y-6">
          
          <div className="space-y-1">
            <h2 className="text-base font-bold text-zinc-950">Enter Access Code</h2>
            <p className="text-zinc-500 text-xs leading-relaxed font-normal">
              Enter the 6-digit dynamic jury access code generated by your hackathon organizer to access the jury grading console.
            </p>
          </div>

          {/* Login Form Client component */}
          <JudgeLoginForm />

          <div className="border-t border-zinc-150 pt-4 text-center">
            <p className="text-[9px] text-zinc-400 font-extrabold uppercase tracking-wider leading-relaxed">
              <span className="text-[#E61E32]">* Note:</span> Codes are valid for exactly 5 minutes from generation. Please request a new code from the organizer if yours has expired.
            </p>
          </div>
        </div>
      </main>

    </div>
  );
}
